class MarkdownBuilder {

    constructor() {
        /** @type {string[]} */
        this.lines = [];
    }

    /**
     * Adds a level 1-6 heading.
     * @param {string} text
     * @param {number} level
     */
    heading(text, level = 1) {
        level = Math.max(1, Math.min(6, level));

        this.lines.push(`${"#".repeat(level)} ${text}`);
        this.lines.push("");

        return this;
    }

    /**
     * Adds plain text.
     * @param {string} text
     */
    text(text = "") {
        this.lines.push(text);
        this.lines.push("");

        return this;
    }

    /**
     * Adds inline code.
     * @param {string} text
     */
    inlineCode(text) {
        this.lines.push(`\`${text}\``);
        this.lines.push("");

        return this;
    }

    /**
     * Adds a markdown code block.
     * @param {string} language
     * @param {string} content
     */
    code(language, content) {

        this.lines.push(`\`\`\`${language || ""}`);
        this.lines.push(content.trimEnd());
        this.lines.push("```");
        this.lines.push("");

        return this;
    }

    /**
     * Adds a horizontal divider.
     */
    divider() {

        this.lines.push("---");
        this.lines.push("");

        return this;
    }


    /**
     * Adds project summary information.
     * @param {{
     * folders:number,
     * files:number,
     * included:number,
     * skipped:number
     * }} summary
     */
    projectSummary(summary) {

        this.heading("Project Summary", 2);

        this.lines.push(
            `- Folders: ${summary.folders ?? 0}`,
            `- Files: ${summary.files ?? 0}`,
            `- Included Source Files: ${summary.included ?? 0}`,
            `- Skipped Files: ${summary.skipped ?? 0}`
        );

        this.lines.push("");

        return this;
    }


    /**
     * Adds folder structure tree.
     * @param {string} tree
     */
    folderStructure(tree) {

        this.heading("Folder Structure", 2);

        this.code("text", tree);

        return this;
    }


    /**
     * Adds a file section.
     * @param {{
     * path:string,
     * language:string,
     * contents:string,
     * truncated?:boolean,
     * remainingCharacters?:number
     * }} file
     */
    file(file) {

        const fileName = file.path.split("/").pop();

        this.heading(`File: ${fileName}`, 2);

        this.text(`Path: \`${file.path}\``);

        let contents = file.contents;

        if (file.truncated) {
            contents +=
                `\n\n... (${file.remainingCharacters} more characters omitted)`;
        }

        this.code(
            file.language,
            contents
        );

        this.divider();

        return this;
    }


    /**
     * Adds a truncated file warning.
     * @param {number} remainingCharacters
     */
    truncated(remainingCharacters) {

        this.text(
            `⚠️ File content truncated. ${remainingCharacters} characters omitted.`
        );

        return this;
    }


    /**
     * Adds a generic warning.
     * @param {string} message
     */
    warning(message) {

        this.text(`⚠️ ${message}`);

        return this;
    }


    /**
     * Adds a generated timestamp.
     */
    generatedBy() {

        this.text(
            "Generated by OutFoxed Copy Folder Structure 🦊"
        );

        return this;
    }


    /**
     * Gets final markdown.
     */
    toString() {

        return this.lines
            .join("\n")
            .trimEnd();

    }

}


module.exports = MarkdownBuilder;